### ISSUE TITLE
InvalidSchema Problem

### ISSUE THREAD

**Issue by eponymic** [josephdc96/PMManager#5]
I have a ProxMox server installed on my local network.  It does not have an external SSL cert.  I have created a .evn file.  The IP is obviously a real IP and the secret is the guid given by proxmox.  Below the .env contents is the traceback, I thought it was related to the SSL value not being set to false originally, but as you can see I corrected that.  This is my first time using the ProxMox API, I'm sure it's my fault.  Any  advise you can offer base on your experience?

`HOST="<IP>" 
PORT= # defaults to 8006 if empty
SSL=false # defaults to true, if you run your server with a self-signed certificate enter 'false' here
TOKEN="proxtag@pam!gui-token=<secret>"

DRIVER='waveshare' # currently the only supported drivers are "console" and "waveshare"
MODEL= "epd2in13v4" # if you chose waveshare you must pick a model. Currently the only supported models are the "epd2in13v4" and "software", a software emulator of the same
`

`(venv) ktc@proxtag:/usr/local/ktc/ProxTag $ python main.py
begin initialize
end initialize
Traceback (most recent call last):
  File "/usr/local/ktc/ProxTag/main.py", line 40, in <module>
    display.initialize()
  File "/usr/local/ktc/ProxTag/drivers/waveshare/waveshare.py", line 115, in initialize
    self.epd.init(lambda: self.after())
  File "/usr/local/ktc/ProxTag/drivers/waveshare/models/waveshare_epd/epd2in13_V4.py", line 214, in init
    after()
  File "/usr/local/ktc/ProxTag/drivers/waveshare/waveshare.py", line 115, in <lambda>
    self.epd.init(lambda: self.after())
                          ^^^^^^^^^^^^
  File "/usr/local/ktc/ProxTag/drivers/waveshare/waveshare.py", line 56, in after
    self.controller.launch()
  File "/usr/local/ktc/ProxTag/controller.py", line 17, in launch
    self.display_vms()
  File "/usr/local/ktc/ProxTag/controller.py", line 20, in display_vms
    vms = self.pve.get_vms()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/ktc/ProxTag/pve.py", line 18, in get_vms
    request = requests.get(url, headers=self.client.headers)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/ktc/ProxTag/venv/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/ktc/ProxTag/venv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/ktc/ProxTag/venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/ktc/ProxTag/venv/lib/python3.11/site-packages/requests/sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/ktc/ProxTag/venv/lib/python3.11/site-packages/requests/sessions.py", line 792, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for '<IP>:8006/api2/json/cluster/resources?type=vm'
`

**Comment by josephdc96** [comment]
Does your HOST environment variable start with `http` or `https`? If not try that and lmk if it changes anything

**Comment by eponymic** [comment]
Glad you pointed that out.  I modified pve.py  as below and the error disapeared.
` self.api_url = f'https://{self.config.host}:{self.config.port}/api2/json'`
